name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: Set up node
      uses: actions/setup-node@v4
    - name: Install newman
      run: npm install -g newman
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
    - name: build test calc
      run: | 
       docker build -t test_calc -f ./src/calc/Dockerfile_test ./src/calc
       docker run -d -p 5000:5000 --name test_calc test_calc
    - name: run test calc
      run: |
       newman run ./tests/calc_ut.postman_collection.json
       docker rm -fv test_calc
    - name: build test string
      run: | 
       docker build -t test_calc -f ./src/string/Dockerfile_test ./src/string
       docker run -d -p 5000:5000 --name test_string test_string
    - name: run test string
      run: |
       newman run ./tests/string_ut.postman_collection.json
       docker rm -fv test_string      

