name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: Set up node
      uses: actions/setup-node@v4
    - name: Install newman
      run: npm install -g newman
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
    - name: Build Calc
      run: docker build -t test_calc -f ./src/calc/Dockerfile_test ./src/calc

